name: validate
version: 1.6.0
author: Mike Mitterer  <office@mikemitterer.at>
description: This class assists in validating method arguments
homepage: https://github.com/MikeMitterer/dart-validate

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:

  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0

dev_dependencies:
  test: any
  grinder: any