name: validate
version: 1.7.0
author: Mike Mitterer  <office@mikemitterer.at>
description: This class assists in validating method arguments
homepage: https://github.com/MikeMitterer/dart-validate

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  grinder: ^0.9.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  build_runner: any
  build_test: ^2.0.0
  build_web_compilers: any
