name: validate
version: 1.7.0
author: Mike Mitterer  <office@mikemitterer.at>
description: This class assists in validating method arguments
homepage: https://github.com/MikeMitterer/dart-validate

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: any
  grinder: any

  console_log_handler: ^1.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  build_runner: any
  build_test: any
  build_web_compilers: any


