name: validate
version: 1.0.2
author: Mike Mitterer  <office@mikemitterer.at>
description: This class assists in validating method arguments
homepage: https://github.com/MikeMitterer/validate
dev_dependencies:
  browser: any
  unittest: any
